export enum EventType {
  // Existing / scenario-related (kept for compatibility)
  NODE_FAILURE = 'NODE_FAILURE',
  LINK_FAILURE = 'LINK_FAILURE',

  // Edit-history events
  NODE_ADDITION = 'NODE_ADDITION',
  NODE_DELETION = 'NODE_DELETION',
  NODE_RENAME = 'NODE_RENAME',
  NODE_MOVE = 'NODE_MOVE',
  NODES_MOVE = 'NODES_MOVE',

  LINK_ADDITION = 'LINK_ADDITION',
  LINK_DELETION = 'LINK_DELETION',
  WEIGHT_CHANGE = 'WEIGHT_CHANGE',

  ROUTE_ENTRY_UPSERT = 'ROUTE_ENTRY_UPSERT',
  ROUTE_ENTRY_DELETE = 'ROUTE_ENTRY_DELETE',

  NETWORK_CLEAR = 'NETWORK_CLEAR',
}
